#!/usr/bin/env sh
# similar to https://golang.org/misc/git/pre-commit

make test || {
    errcode=$?
    echo "tests failed"
    exit $errcode
}


files=$(git diff --cached --name-only --diff-filter=ACM | egrep -i '*.go$')
test -z "$file" && exit

unformatted=$(goimports -l $files)
text -z "$unformatted" && exit

echo "Unformatted files found, printing them to stdout:" >&2
i=0
for file in $unformatted; do
    i=$(expr $i + 1)
    echo "$file"
done
exit $i
